export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: true,
    lightTextDesc: false,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transaction with zero fees',
    description: 'Get access to our exclusive app that allows you to send and receive money without any fees. ',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../../images/svg-1.svg'),
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: false,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Login to you account at any time ',
    description: 'We have you covered no matter where you are located. All you need is an internet connection and a phone or computer.',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../../images/svg-2.svg'),
    alt: 'mobile',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: true,
    lightTextDesc: false,
    topLine: 'Join Our Team',
    headline: 'Creating an account is extremely easy',
    description: "Get everything set up and ready in under 10 minutes. All you need to do is add your information and you're ready to go  ",
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../../images/svg-3.svg'),
    alt: 'bank',
    dark: false,
    primary: false,
    darkText: true,
}

